Add preserve ACL grants feature
clyso/chorus pull request #51
Opened 2024-11-26 13:40 UTC by pablo1664

Add option syncACLGrants to ensure all ACL bucket/object have grants synchronized.
Default value to false

2024-11-26 16:07 UTC, aiivashchenko commented
Hi @pablo1664! Can you elaborate a little bit more on a PR? I.e. what is the issue you have faced, and how is this change resolving it?

2024-11-26 19:18 UTC, pablo1664 commented
Hi,
Sorry, yes little more context, I have 2 ceph cluster, one legacy and new one.
The needed is to migrate all bucket to the new one.
One admin user is configured that is the owner of all buckets, and many users that have full control on multiple buckets.
ACL are used by default and some buckets have also policies configured.

On the worker, source and destination use same user ID to access buckets.

When I add bucket replication, object ACL are not the same from the source, by the way Object owner have to be the same ID used by the worked.

Bucket ACL seems to be good, but all grants on Object ACL are set with only the ID used by the worker.
If bucket have only ACL configured Users can no longer GET/PUT on existing object.

Finaly this fix can work in this case, but after reflection can not the good way on different configuration with other provider. 
Probably add an option to replicate ACL Grants source if needed.

2024-11-28 13:57 UTC, arttor requested changes

2024-11-28 13:57 UTC, arttor commented on docker-compose/s3-credentials.yaml
> +      syncACLGrants: false
I really like the idea of making this behaviour optional and configuring it with a feature flag. 
Can you please do the following changes to comply with existing chorus feature flags:
- rename to something like `preserveACLGrants`
- move this config parameter from storages config to [features config](https://github.com/clyso/chorus/blob/main/pkg/features/features.go). 
- move config default value from `docker-compose/s3-credentials.yaml` to [pkg/config/config.yaml](https://github.com/clyso/chorus/blob/main/pkg/config/config.yaml#L31-L37).

2024-11-28 19:31 UTC, arttor approved these changes

2024-11-28 19:36 UTC, merged